language: ruby
rvm:
  - "2.6.5"
before_install:
    - gem install bundler
services:
  - postgresql
script:
    - bundle exec rake db:migrate
    - bundle exec rspec
before_script:
  - psql -c 'create database umed_test;' -U postgres
