development:
  adapter: postgresql
  encoding: unicode
  database: umed_development
  pool: 5
  host: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: umed_test
  pool: 5
  host: localhost
